"""
Profile the Phase 1 NYC Open Data samples without modifying them.
This module provides utilities to profile sample data from NYC Open Data without modifying the original files.

The profile report is written to `docs/project_documents/data_profile.md` and can be regenerated by running this script directly.
The report includes counts of missing values, duplicate records, and other data quality metrics for both the inspection and complaint datasets.
It also includes a harmonization profile for restaurant names, which applies syntax normalization and reviewed alias rules to identify potential co-branded names and fast-food brands

"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd

from name_normalization import (
    brand_candidates,
    canonicalize_name,
    load_name_references,
    normalize_name,
)

# Figures out where the main project folder is located on your computer so it can find files easily.
# Sets up exact file locations for your raw data samples (inspections and 311 complaints), reference files (brand aliases, fast-food lists), and where the final report (data_profile.md) should be saved.

PROJECT_ROOT = Path(__file__).resolve().parents[1]

SAMPLE_DIRECTORY = PROJECT_ROOT / "data" / "samples"
INSPECTION_SAMPLE_PATH = SAMPLE_DIRECTORY / "dohmh_inspections_sample.json"
COMPLAINT_SAMPLE_PATH = SAMPLE_DIRECTORY / "311_food_pest_sample.json"
REPORT_PATH = PROJECT_ROOT / "docs" / "project_documents" / "data_profile.md"

REFERENCE_DIRECTORY = PROJECT_ROOT / "data" / "reference"

INSPECTION_KEY_FIELDS = [
    "camis",
    "dba",
    "boro",
    "building",
    "street",
    "zipcode",
    "latitude",
    "longitude",
    "cuisine_description",
    "inspection_date",
    "action",
    "violation_code",
    "violation_description",
    "critical_flag",
    "score",
    "grade",
    "grade_date",
]

COMPLAINT_KEY_FIELDS = [
    "unique_key",
    "created_date",
    "complaint_type",
    "descriptor",
    "incident_zip",
    "latitude",
    "longitude",
    "borough",
    "status",
]

EXPECTED_COMPLAINT_TYPES = {
    "Food Poisoning",
    "Rodent",
    "Food Establishment",
}

# Opens a JSON file, reads it, and makes sure it's actually a list of objects (dictionaries). If the file format is broken, it raises an error.
def load_records(path: Path) -> list[dict[str, Any]]:
    """Load and validate a JSON-list sample."""

    with path.open(mode="r", encoding="utf-8") as input_file:
        records = json.load(input_file)

    if not isinstance(records, list):
        raise TypeError(
            f"{path.name} must contain a JSON list."
        )

    if not all(isinstance(record, dict) for record in records):
        raise TypeError(f"Every record in {path.name} must be an object.")

    return records

# Converts a list of dictionaries into a pandas DataFrame, replacing any blank strings with missing values (pd.NA).
def create_dataframe(records: list[dict[str, Any]]) -> pd.DataFrame:
    """Convert records to a DataFrame and treat blanks as missing."""

    return pd.DataFrame(records).replace(r"^\s*$", pd.NA, regex=True)

# Checking Data Quality
# The below functions analyze different parts of the data to see how clean or messy it is:
# exact_duplicate_count(): Checks if there are any exact, identical rows repeated in the file and counts them.
def exact_duplicate_count(records: list[dict[str, Any]]) -> int:
    """Count completely identical JSON records."""

    canonical_records = {
        json.dumps(record, sort_keys=True, separators=(",", ":"))
        for record in records
    }

    return len(records) - len(canonical_records)

# missing_value_profile(): Counts how many items are missing for each important field and calculates the missing percentage.
def missing_value_profile(dataframe: pd.DataFrame, fields: list[str]) -> pd.DataFrame:
    """Calculate missing counts for the planned fields."""

    total_rows = len(dataframe)
    rows: list[dict[str, Any]] = []

    for field in fields:
        missing_count = (
            int(dataframe[field].isna().sum())
            if field in dataframe.columns
            else total_rows
        )

        rows.append(
            {
                "field": field,
                "missing_count": missing_count,
                "missing_percent": (
                    round(missing_count / total_rows * 100, 2)
                    if total_rows
                    else 0.0
                ),
            }
        )

    return pd.DataFrame(rows)

# value_counts_table(): Counts how often each unique value appears (like how many restaurants got an "A" grade versus a "B" grade).
def value_counts_table(dataframe: pd.DataFrame, field: str) -> pd.DataFrame:
    """Return value frequencies, including missing values."""

    if field not in dataframe.columns:
        return pd.DataFrame(
            [{field: "<field absent>", "row_count": len(dataframe)}]
        )

    values = (
        dataframe[field]
        .fillna("<missing>")
        .astype(str)
        .value_counts(dropna=False)
        .rename_axis(field)
        .reset_index(name="row_count")
    )

    return values

# date_profile(): Checks if dates can be read properly, finds the earliest and latest dates, and looks for broken dates or special placeholder dates (like the year 1900).
def date_profile(dataframe: pd.DataFrame, field: str) -> dict[str, Any]:
    """Profile whether a field can be parsed as a date."""

    parsed_dates = pd.to_datetime(dataframe[field], errors="coerce")
    valid_dates = parsed_dates.dropna()
    source_present = int(dataframe[field].notna().sum())
    invalid_count = int(source_present - parsed_dates.notna().sum())
    sentinel_1900_count = int((parsed_dates.dt.year == 1900).sum())

    return {
        "minimum": valid_dates.min().isoformat() if not valid_dates.empty else "<none>",
        "maximum": valid_dates.max().isoformat() if not valid_dates.empty else "<none>",
        "invalid_count": invalid_count,
        "sentinel_1900_count": sentinel_1900_count,
    }

# coordinate_profile(): Checks latitude and longitude to see how many coordinates are missing, set to zero, or located completely outside of New York City.
def coordinate_profile(
    dataframe: pd.DataFrame,
) -> dict[str, int]:
    """Measure missing, zero, and out-of-NYC coordinates."""

    latitude = pd.to_numeric(dataframe["latitude"], errors="coerce")
    longitude = pd.to_numeric(dataframe["longitude"], errors="coerce")
    missing_coordinates = latitude.isna() | longitude.isna()
    zero_coordinates = (latitude == 0) | (longitude == 0)

    outside_nyc = (
        ~missing_coordinates
        & ~zero_coordinates
        & (
            ~latitude.between(40.4, 41.0)
            | ~longitude.between(-74.3, -73.6)
        )
    )

    return {
        "missing": int(missing_coordinates.sum()),
        "zero": int(zero_coordinates.sum()),
        "outside_nyc_bounds": int(outside_nyc.sum()),
        "usable": int(
            (~missing_coordinates & ~zero_coordinates & ~outside_nyc).sum()
        ),
    }

# numeric_profile(): Checks number fields (like inspection scores) to make sure they are actually numbers and counts any non-numeric text.
def numeric_profile(dataframe: pd.DataFrame, field: str) -> dict[str, Any]:
    """Check whether source values can become numeric."""

    numeric_values = pd.to_numeric(dataframe[field], errors="coerce")
    source_present = int(dataframe[field].notna().sum())
    non_numeric_count = int(source_present - numeric_values.notna().sum())
    valid_values = numeric_values.dropna()

    return {
        "minimum": float(valid_values.min()) if not valid_values.empty else None,
        "maximum": float(valid_values.max()) if not valid_values.empty else None,
        "non_numeric_count": non_numeric_count,
    }


# inspection_grain_profile(): Checks for repeated rows that belong to the same inspection, helping to identify potential data duplication issues.
def inspection_grain_profile(dataframe: pd.DataFrame) -> dict[str, int]:
    """Measure repeated rows belonging to the same inspection."""

    grouping_fields = ["camis", "inspection_date", "inspection_type"]
    group_sizes = dataframe.groupby(grouping_fields, dropna=False).size()

    return {
        "estimated_inspection_events": len(group_sizes),
        "events_with_multiple_rows": int((group_sizes > 1).sum()),
        "largest_rows_per_event": (
            int(group_sizes.max()) if not group_sizes.empty else 0
        ),
    }

# restaurant_name_profile(): Checks if the same restaurant ID (camis) ever has multiple different names (dba) in the sample.
def restaurant_name_profile(dataframe: pd.DataFrame) -> dict[str, int]:
    """Find CAMIS values associated with multiple DBA names."""

    names_per_restaurant = dataframe.groupby("camis")["dba"].nunique(
        dropna=True
    )

    return {
        "unique_camis": int(dataframe["camis"].nunique(dropna=True)),
        "camis_with_multiple_names": int((names_per_restaurant > 1).sum()),
    }

# name_harmonization_profile(): This function cleans up and standardizes restaurant names. 
# It removes weird punctuation, applies known nicknames or aliases (e.g., matching a brand name properly), checks for co-branded restaurants (like a store with two brands inside), and flags names that contain separators like & or AND so you can review them manually.
def name_harmonization_profile(dataframe: pd.DataFrame) -> dict[str, Any]:
    """Profile shared normalization, aliases, and reviewed co-brands."""

    aliases, co_brands, fast_food_brands = load_name_references(
        REFERENCE_DIRECTORY
    )

    restaurants = dataframe[["camis", "dba"]].drop_duplicates().copy()
    restaurants["name_syntax_normalized"] = restaurants["dba"].map(normalize_name)
    restaurants["name_normalized"] = restaurants["dba"].map(
        lambda name: canonicalize_name(name, aliases)
    )
    restaurants["brand_candidates"] = restaurants["dba"].map(
        lambda name: brand_candidates(name, aliases, co_brands)
    )
    restaurants["confirmed_fast_food_brands"] = restaurants["brand_candidates"].map(
        lambda candidates: tuple(
            brand for brand in candidates if brand in fast_food_brands
        )
    )

    alias_rows = restaurants[
        restaurants["name_syntax_normalized"] != restaurants["name_normalized"]
    ]
    co_brand_rows = restaurants[
        restaurants["name_syntax_normalized"].isin(co_brands)
    ]

    collision_groups = (
        restaurants.groupby("name_normalized", dropna=False)["dba"]
        .agg(lambda values: tuple(sorted(set(values))))
    )
    collision_groups = collision_groups[collision_groups.map(len) > 1]
    collision_table = pd.DataFrame(
        [
            {
                "name_normalized": name,
                "source_dba_values": " | ".join(source_names),
            }
            for name, source_names in collision_groups.items()
        ]
    )

    co_brand_table = pd.DataFrame(
        [
            {
                "location_name_normalized": location_name,
                "brands_preserved": " + ".join(brand_names),
                "sample_camis": int(
                    co_brand_rows.loc[
                        co_brand_rows["name_syntax_normalized"] == location_name,
                        "camis",
                    ].nunique()
                ),
            }
            for location_name, brand_names in co_brands.items()
        ]
    )

    separator_mask = restaurants["dba"].str.contains(
        r"[/&,]|\bAND\b",
        case=False,
        regex=True,
        na=False,
    )
    separator_table = (
        restaurants.loc[
            separator_mask,
            ["dba", "name_syntax_normalized", "camis"],
        ]
        .groupby(["dba", "name_syntax_normalized"], as_index=False)["camis"]
        .nunique()
        .rename(columns={"camis": "sample_camis"})
        .sort_values("dba")
    )
    separator_table["policy"] = separator_table["name_syntax_normalized"].map(
        lambda name: (
            "REVIEWED CO-BRAND"
            if name in co_brands
            else "REVIEW ONLY - NOT SPLIT"
        )
    )

    return {
        "unique_source_names": int(restaurants["dba"].nunique()),
        "unique_syntax_names": int(restaurants["name_syntax_normalized"].nunique()),
        "unique_canonical_names": int(restaurants["name_normalized"].nunique()),
        "alias_camis": int(alias_rows["camis"].nunique()),
        "co_brand_camis": int(co_brand_rows["camis"].nunique()),
        "confirmed_fast_food_camis": int(
            restaurants.loc[
                restaurants["confirmed_fast_food_brands"].map(bool),
                "camis",
            ].nunique()
        ),
        "separator_names": int(restaurants.loc[separator_mask, "dba"].nunique()),
        "collision_table": collision_table,
        "co_brand_table": co_brand_table,
        "separator_table": separator_table,
    }

# format_table(): Converts a Pandas table into a clean Markdown code block so it looks neat in the final document.
def format_table(dataframe: pd.DataFrame) -> str:
    """Format a DataFrame without adding another dependency."""

    return "```\n" + dataframe.to_string(index=False) + "\n```"

# build_report(): This is the master function that runs all the checks above on both the inspection data and the 311 complaint data. It puts everything together into a structured list of text lines with headings, summary counts, tables, and a list of initial data-quality decisions (rules on how to handle missing data, dates, coordinates, etc.).
def build_report(
    inspection_records: list[dict[str, Any]],
    complaint_records: list[dict[str, Any]],
) -> str:
    """Build the Phase 1 Markdown profile report."""

    inspections = create_dataframe(inspection_records)
    complaints = create_dataframe(complaint_records)

    inspection_date_results = date_profile(inspections, "inspection_date")
    complaint_date_results = date_profile(complaints, "created_date")
    inspection_coordinate_results = coordinate_profile(inspections)
    complaint_coordinate_results = coordinate_profile(complaints)
    score_results = numeric_profile(inspections, "score")
    grain_results = inspection_grain_profile(inspections)
    name_results = restaurant_name_profile(inspections)
    harmonization_results = name_harmonization_profile(inspections)

    duplicate_complaint_ids = int(complaints["unique_key"].duplicated().sum())
    complaint_types = set(complaints["complaint_type"].dropna())
    unexpected_complaint_types = complaint_types - EXPECTED_COMPLAINT_TYPES

    lines = [
        "# Phase 1 Data Profile",
        "",
        "This report profiles the small NYC Open Data "
        "samples used for schema and data-quality exploration.",
        "",
        "The samples are not the full production datasets.",
        "",
        "## Sample summary",
        "",
        f"- Inspection rows: {len(inspections):,}",
        f"- Inspection fields observed: "
        f"{len(inspections.columns):,}",
        f"- Unique restaurants (`camis`): "
        f"{name_results['unique_camis']:,}",
        f"- 311 rows: {len(complaints):,}",
        f"- 311 fields observed: "
        f"{len(complaints.columns):,}",
        "",
        "## Inspection fields observed",
        "",
        ", ".join(sorted(inspections.columns)),
        "",
        "## 311 fields observed",
        "",
        ", ".join(sorted(complaints.columns)),
        "",
        "## Inspection key-field missingness",
        "",
        format_table(
            missing_value_profile(
                inspections,
                INSPECTION_KEY_FIELDS,
            )
        ),
        "",
        "## 311 key-field missingness",
        "",
        format_table(
            missing_value_profile(
                complaints,
                COMPLAINT_KEY_FIELDS,
            )
        ),
        "",
        "## Inspection borough values",
        "",
        format_table(
            value_counts_table(
                inspections,
                "boro",
            )
        ),
        "",
        "## Inspection grade values",
        "",
        format_table(
            value_counts_table(
                inspections,
                "grade",
            )
        ),
        "",
        "## Inspection critical-flag values",
        "",
        format_table(
            value_counts_table(
                inspections,
                "critical_flag",
            )
        ),
        "",
        "## 311 complaint types",
        "",
        format_table(
            value_counts_table(
                complaints,
                "complaint_type",
            )
        ),
        "",
        "## 311 borough values",
        "",
        format_table(
            value_counts_table(
                complaints,
                "borough",
            )
        ),
        "",
        "## 311 status values",
        "",
        format_table(
            value_counts_table(
                complaints,
                "status",
            )
        ),
        "",
        "## Duplicate and grain checks",
        "",
        f"- Exact duplicate inspection rows: "
        f"{exact_duplicate_count(inspection_records):,}",
        f"- Estimated inspection events: "
        f"{grain_results['estimated_inspection_events']:,}",
        f"- Inspection events with multiple violation rows: "
        f"{grain_results['events_with_multiple_rows']:,}",
        f"- Largest number of rows for one inspection event: "
        f"{grain_results['largest_rows_per_event']:,}",
        f"- CAMIS values with multiple DBA names in the sample: "
        f"{name_results['camis_with_multiple_names']:,}",
        f"- Exact duplicate 311 rows: "
        f"{exact_duplicate_count(complaint_records):,}",
        f"- Duplicate 311 `unique_key` values: "
        f"{duplicate_complaint_ids:,}",
        "",
        "## Restaurant-name harmonization",
        "",
        "This profile applies the same syntax normalization and reviewed "
        "alias rules used to build the fast-food brand reference. "
        "Co-brands are expanded only through the reviewed association file; "
        "punctuation and words such as `AND` are not splitting rules.",
        "",
        f"- Unique source DBA values: "
        f"{harmonization_results['unique_source_names']:,}",
        f"- Unique values after syntax normalization: "
        f"{harmonization_results['unique_syntax_names']:,}",
        f"- Unique values after reviewed aliases: "
        f"{harmonization_results['unique_canonical_names']:,}",
        f"- CAMIS values changed by a reviewed alias: "
        f"{harmonization_results['alias_camis']:,}",
        f"- CAMIS values with a reviewed co-brand association: "
        f"{harmonization_results['co_brand_camis']:,}",
        f"- CAMIS values exactly matching at least one fast-food brand: "
        f"{harmonization_results['confirmed_fast_food_camis']:,}",
        f"- Distinct names containing a possible separator: "
        f"{harmonization_results['separator_names']:,}",
        "",
        "### Source names merged by normalization or aliases",
        "",
        format_table(harmonization_results["collision_table"]),
        "",
        "### Reviewed co-brand associations",
        "",
        format_table(harmonization_results["co_brand_table"]),
        "",
        "The separator count is a review queue, not a co-brand count. For "
        "example, `FRESH AND CO` and `JOE & THE JUICE` are single names.",
        "",
        "### Separator review queue",
        "",
        format_table(harmonization_results["separator_table"]),
        "",
        "## Date checks",
        "",
        f"- Inspection minimum date: "
        f"{inspection_date_results['minimum']}",
        f"- Inspection maximum date: "
        f"{inspection_date_results['maximum']}",
        f"- Unparseable inspection dates: "
        f"{inspection_date_results['invalid_count']:,}",
        f"- `1900-01-01` inspection sentinel rows: "
        f"{inspection_date_results['sentinel_1900_count']:,}",
        f"- 311 minimum created date: "
        f"{complaint_date_results['minimum']}",
        f"- 311 maximum created date: "
        f"{complaint_date_results['maximum']}",
        f"- Unparseable 311 created dates: "
        f"{complaint_date_results['invalid_count']:,}",
        "",
        "## Coordinate checks",
        "",
        "### Inspections",
        "",
        f"- Missing coordinate pairs: "
        f"{inspection_coordinate_results['missing']:,}",
        f"- Zero coordinate pairs: "
        f"{inspection_coordinate_results['zero']:,}",
        f"- Outside approximate NYC bounds: "
        f"{inspection_coordinate_results['outside_nyc_bounds']:,}",
        f"- Usable coordinate pairs: "
        f"{inspection_coordinate_results['usable']:,}",
        "",
        "### 311 complaints",
        "",
        f"- Missing coordinate pairs: "
        f"{complaint_coordinate_results['missing']:,}",
        f"- Zero coordinate pairs: "
        f"{complaint_coordinate_results['zero']:,}",
        f"- Outside approximate NYC bounds: "
        f"{complaint_coordinate_results['outside_nyc_bounds']:,}",
        f"- Usable coordinate pairs: "
        f"{complaint_coordinate_results['usable']:,}",
        "",
        "## Inspection score checks",
        "",
        f"- Minimum parseable score: "
        f"{score_results['minimum']}",
        f"- Maximum parseable score: "
        f"{score_results['maximum']}",
        f"- Non-numeric populated scores: "
        f"{score_results['non_numeric_count']:,}",
        "",
        "## Complaint-filter validation",
        "",
        f"- Complaint types returned: "
        f"{sorted(complaint_types)}",
        f"- Unexpected complaint types: "
        f"{sorted(unexpected_complaint_types)}",
        "",
        "## Dashboard-field mapping",
        "",
        "- Page 1 uses restaurant, borough, cuisine, grade, "
        "score, critical flag, action, and violation fields.",
        "- Page 2 uses inspection and complaint dates, boroughs, "
        "complaint types, critical violations, and coordinates.",
        "- Page 3 uses CAMIS, restaurant name, address, ZIP, "
        "cuisine, grade, inspection date, score, and violations.",
        "- Page 4 will use historical inspection fields to build "
        "the B/C-risk features.",
        "",
        "## Initial data-quality decisions",
        "",
        "1. Preserve the original Bronze JSON without modification.",
        "2. Parse dates and numeric values explicitly in Silver.",
        "3. Treat `1900-01-01` as a not-yet-inspected sentinel, "
        "not a real inspection date.",
        "4. Preserve legitimate multiple violation rows belonging "
        "to one inspection event.",
        "5. Deduplicate exact records and duplicate 311 keys using "
        "documented rules.",
        "6. Standardize borough capitalization between sources.",
        "7. Treat missing, zero, or out-of-range coordinates as "
        "unusable for geospatial matching.",
        "8. Preserve source grades such as N, Z, and P in Silver; "
        "filter or map them only when building graded Gold metrics.",
        "9. Do not calculate dashboard KPIs from this recent "
        "1,000-row sample.",
        "10. Use the later historical ingestion for three-year "
        "grade history, correlation, and ML training.",
        "",
    ]

    return "\n".join(lines)

# Running the Program
# main(): The starting point of the script when you run it:
# Loads the inspection records and 311 complaint records from their files.
# Runs build_report() to generate the markdown content.
# Creates the docs folder if it doesn't exist yet.
# Saves everything into data_profile.md and prints a success message in your terminal.

def main() -> None:
    """Load samples and write a reproducible profile report."""

    inspection_records = load_records(INSPECTION_SAMPLE_PATH)
    complaint_records = load_records(COMPLAINT_SAMPLE_PATH)
    report = build_report(inspection_records, complaint_records)

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")

    print("Data profile complete.")
    print(f"Report: {REPORT_PATH}")


if __name__ == "__main__":
    main()
